id: AE5EE157B
title: 'Cymbals to Invoke a Compassionate Response: A Prayer for Swift Rebirth of
  Khandro Tsering Chödrön'
type: translation
pechas:
- I4EDA1BA8
- IFF8CF49F
- I917FD718
- IF9566976
source_metadata:
  languages:
  - en
  - es
  - fr
  - bo
  datatype: PlainText
  created_at: 2023-01-04 12:48:54.227892
  last_modified_at: 2023-01-04 12:48:54.227910
  collections:
  - Khandro Tsering Chödrön Series
  - Works of Tibetan Masters
alignment_to_base:
  I4EDA1BA8/AA2C: '4066'
  IFF8CF49F/D823: '4066'
  I917FD718/F04C: '4066'
  IF9566976/27FF: '4066'
